language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

git:
  submodules: false

warnings_are_errors: true
env:
  global:
    - _R_CHECK_CRAN_INCOMING_=FALSE

r_github_packages:
  - r-simmer/simmer
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'

before_script:
  - mkdir -p .docs/extensions/bricks
after_script:
  - rm -rf .docs/extensions
